// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cum_clustprop
NumericVector cum_clustprop(const NumericMatrix P1);
RcppExport SEXP _vimixr_cum_clustprop(SEXP P1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type P1(P1SEXP);
    rcpp_result_gen = Rcpp::wrap(cum_clustprop(P1));
    return rcpp_result_gen;
END_RCPP
}
// cum_clustprop_var
NumericVector cum_clustprop_var(const NumericMatrix P1);
RcppExport SEXP _vimixr_cum_clustprop_var(SEXP P1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type P1(P1SEXP);
    rcpp_result_gen = Rcpp::wrap(cum_clustprop_var(P1));
    return rcpp_result_gen;
END_RCPP
}
// lower_tri_stats
Rcpp::NumericVector lower_tri_stats(const Rcpp::NumericMatrix& M);
RcppExport SEXP _vimixr_lower_tri_stats(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(lower_tri_stats(M));
    return rcpp_result_gen;
END_RCPP
}
// mat_mult
SEXP mat_mult(SEXP A, SEXP B, bool transpose_A, bool transpose_B);
RcppExport SEXP _vimixr_mat_mult(SEXP ASEXP, SEXP BSEXP, SEXP transpose_ASEXP, SEXP transpose_BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< SEXP >::type B(BSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose_A(transpose_ASEXP);
    Rcpp::traits::input_parameter< bool >::type transpose_B(transpose_BSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_mult(A, B, transpose_A, transpose_B));
    return rcpp_result_gen;
END_RCPP
}
// mat_mult_t
Eigen::MatrixXd mat_mult_t(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B, const Eigen::MatrixXd& C);
RcppExport SEXP _vimixr_mat_mult_t(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_mult_t(A, B, C));
    return rcpp_result_gen;
END_RCPP
}
// quadratic_form_diag
Eigen::VectorXd quadratic_form_diag(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B);
RcppExport SEXP _vimixr_quadratic_form_diag(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(quadratic_form_diag(A, B));
    return rcpp_result_gen;
END_RCPP
}
// sparse_cov_op
double sparse_cov_op(const Rcpp::NumericMatrix& X, const Rcpp::NumericMatrix& P, const Rcpp::NumericMatrix& inv_C0, const Rcpp::NumericMatrix& L1);
RcppExport SEXP _vimixr_sparse_cov_op(SEXP XSEXP, SEXP PSEXP, SEXP inv_C0SEXP, SEXP L1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type inv_C0(inv_C0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type L1(L1SEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_cov_op(X, P, inv_C0, L1));
    return rcpp_result_gen;
END_RCPP
}
// sweep_3D
NumericVector sweep_3D(NumericVector A, NumericVector R, IntegerVector dims, int n_threads);
RcppExport SEXP _vimixr_sweep_3D(SEXP ASEXP, SEXP RSEXP, SEXP dimsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_3D(A, R, dims, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// t_mat_mult
Eigen::MatrixXd t_mat_mult(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B, const Eigen::MatrixXd& C);
RcppExport SEXP _vimixr_t_mat_mult(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(t_mat_mult(A, B, C));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vimixr_cum_clustprop", (DL_FUNC) &_vimixr_cum_clustprop, 1},
    {"_vimixr_cum_clustprop_var", (DL_FUNC) &_vimixr_cum_clustprop_var, 1},
    {"_vimixr_lower_tri_stats", (DL_FUNC) &_vimixr_lower_tri_stats, 1},
    {"_vimixr_mat_mult", (DL_FUNC) &_vimixr_mat_mult, 4},
    {"_vimixr_mat_mult_t", (DL_FUNC) &_vimixr_mat_mult_t, 3},
    {"_vimixr_quadratic_form_diag", (DL_FUNC) &_vimixr_quadratic_form_diag, 2},
    {"_vimixr_sparse_cov_op", (DL_FUNC) &_vimixr_sparse_cov_op, 4},
    {"_vimixr_sweep_3D", (DL_FUNC) &_vimixr_sweep_3D, 4},
    {"_vimixr_t_mat_mult", (DL_FUNC) &_vimixr_t_mat_mult, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_vimixr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
