// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cum_clustprop
NumericVector cum_clustprop(const NumericMatrix P1);
RcppExport SEXP _vimixr_cum_clustprop(SEXP P1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type P1(P1SEXP);
    rcpp_result_gen = Rcpp::wrap(cum_clustprop(P1));
    return rcpp_result_gen;
END_RCPP
}
// cum_clustprop_var
NumericVector cum_clustprop_var(const NumericMatrix P1);
RcppExport SEXP _vimixr_cum_clustprop_var(SEXP P1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type P1(P1SEXP);
    rcpp_result_gen = Rcpp::wrap(cum_clustprop_var(P1));
    return rcpp_result_gen;
END_RCPP
}
// eBayes_init
void eBayes_init(const Eigen::VectorXd& Rk, const Eigen::MatrixXd& PSk, const Eigen::MatrixXd& Sk);
RcppExport SEXP _vimixr_eBayes_init(SEXP RkSEXP, SEXP PSkSEXP, SEXP SkSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Rk(RkSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type PSk(PSkSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Sk(SkSEXP);
    eBayes_init(Rk, PSk, Sk);
    return R_NilValue;
END_RCPP
}
// eBayes_run
Eigen::VectorXd eBayes_run(const Eigen::VectorXd& a_vec);
RcppExport SEXP _vimixr_eBayes_run(SEXP a_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type a_vec(a_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(eBayes_run(a_vec));
    return rcpp_result_gen;
END_RCPP
}
// mat_mult
Eigen::MatrixXd mat_mult(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B);
RcppExport SEXP _vimixr_mat_mult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_mult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// mat_mult_t
Eigen::MatrixXd mat_mult_t(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B, const Eigen::MatrixXd& C);
RcppExport SEXP _vimixr_mat_mult_t(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_mult_t(A, B, C));
    return rcpp_result_gen;
END_RCPP
}
// quadratic_form_diag
Eigen::VectorXd quadratic_form_diag(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B);
RcppExport SEXP _vimixr_quadratic_form_diag(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(quadratic_form_diag(A, B));
    return rcpp_result_gen;
END_RCPP
}
// sweep_3D
NumericVector sweep_3D(NumericVector A, NumericVector R, IntegerVector dims, int n_threads);
RcppExport SEXP _vimixr_sweep_3D(SEXP ASEXP, SEXP RSEXP, SEXP dimsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_3D(A, R, dims, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// t_mat_mult
Eigen::MatrixXd t_mat_mult(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B, const Eigen::MatrixXd& C);
RcppExport SEXP _vimixr_t_mat_mult(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(t_mat_mult(A, B, C));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vimixr_cum_clustprop", (DL_FUNC) &_vimixr_cum_clustprop, 1},
    {"_vimixr_cum_clustprop_var", (DL_FUNC) &_vimixr_cum_clustprop_var, 1},
    {"_vimixr_eBayes_init", (DL_FUNC) &_vimixr_eBayes_init, 3},
    {"_vimixr_eBayes_run", (DL_FUNC) &_vimixr_eBayes_run, 1},
    {"_vimixr_mat_mult", (DL_FUNC) &_vimixr_mat_mult, 2},
    {"_vimixr_mat_mult_t", (DL_FUNC) &_vimixr_mat_mult_t, 3},
    {"_vimixr_quadratic_form_diag", (DL_FUNC) &_vimixr_quadratic_form_diag, 2},
    {"_vimixr_sweep_3D", (DL_FUNC) &_vimixr_sweep_3D, 4},
    {"_vimixr_t_mat_mult", (DL_FUNC) &_vimixr_t_mat_mult, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_vimixr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
