# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cum_clustprop <- function(P1) {
    .Call(`_vimixr_cum_clustprop`, P1)
}

cum_clustprop_var <- function(P1) {
    .Call(`_vimixr_cum_clustprop_var`, P1)
}

#' @export
quadratic_form_diag <- function(A, B) {
    .Call(`_vimixr_quadratic_form_diag`, A, B)
}

