# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cum_clustprop
#'
#' Calculate the columnwise sum of rowwise cummulative probability
#' @param P1 probability matrix
#' @return rowwise cummulative probability
#' @export
cum_clustprop <- function(P1) {
    .Call(`_vimixr_cum_clustprop`, P1)
}

#' cum_clustprop_var
#'
#' Calculate the columnwise sum of rowwise cummulative probability for variance
#' @param P1 probability matrix
#' @return rowwise cummulative probability for variance
#' @export
cum_clustprop_var <- function(P1) {
    .Call(`_vimixr_cum_clustprop_var`, P1)
}

#' lower_tri_stats
#'
#' Extract lower diagonal elements of a Matrix, and perform sum, squared sum and log sum
#' @param M matrix
#' @return a vector of sum, squared sum and log sum elements
#' @export
lower_tri_stats <- function(M) {
    .Call(`_vimixr_lower_tri_stats`, M)
}

#' mat_mult
#'
#' Calculate matrix multiplication with optional transposition.
#' @param A matrix or vector
#' @param B matrix or vector
#' @param transpose_A transpose A before multiplying
#' @param transpose_B transpose B before multiplying
#' @return A %*% B (or variant), as vector if either input was a vector
#' @export
mat_mult <- function(A, B, transpose_A = FALSE, transpose_B = FALSE) {
    .Call(`_vimixr_mat_mult`, A, B, transpose_A, transpose_B)
}

#' mat_mult_t
#'
#' Calculate a combination of matrix multiplications
#' @param A matrix
#' @param B matrix
#' @param C matrix
#' @return A %*% B %*% t(C)
#' @export
mat_mult_t <- function(A, B, C) {
    .Call(`_vimixr_mat_mult_t`, A, B, C)
}

#' quadratic_form_diag
#'
#' Calculate a combination of matrix multiplications
#' @param A matrix
#' @param B matrix
#' @return diag(A %*% B %*% t(A))
#' @export
quadratic_form_diag <- function(A, B) {
    .Call(`_vimixr_quadratic_form_diag`, A, B)
}

#' sparse_cov_op
#'
#' Calculate the sum, squared sum and log sum of off-diagonal vector elements from the covariance array
#' @param X data matrix
#' @param P probability allocation matrix
#' @param inv_C0 matrix corresponding diagonal elements of the cluster precision matrices
#' @param L1 cluster mean matrix
#' @return likelihood term calculation in elbo
#' @export
sparse_cov_op <- function(X, P, inv_C0, L1) {
    .Call(`_vimixr_sparse_cov_op`, X, P, inv_C0, L1)
}

#' sweep_3D
#'
#' A C++ alternative of sweep() function from base R
#' @param A a 3D array
#' @param R a vector
#' @param dims dimensions in 3D
#' @param n_threads number of threads
#' @return sweep(A, 3, R, "*")
#' @export
sweep_3D <- function(A, R, dims, n_threads = 4L) {
    .Call(`_vimixr_sweep_3D`, A, R, dims, n_threads)
}

#' t_mat_mult
#'
#' Calculate a combination of matrix multiplications
#' @param A matrix
#' @param B matrix
#' @param C matrix
#' @return t(A) %*% B %*% C
#' @export
t_mat_mult <- function(A, B, C) {
    .Call(`_vimixr_t_mat_mult`, A, B, C)
}

